### ISSUE TITLE
Quality management in charts

### ISSUE THREAD

**Issue by stephanepilla** [predixdesignsystem/px-vis-timeseries#16]
The timeseries API always return 3 properties per datapoint : timestamp, value, quality.

In your charts, you don't seem to care about the quality of the datapoints.
In my opinion, a value doesn't mean anything if we don't know its quality(valid, invalid, doubtful, ...).

It would be a very usefull feature to display differently the invalid/doubtful datapoints (with a different color or thickness for a line series).

**Comment by nonmetalhail** [comment]
FYI: This is currently under investigation for design and engineering and will be considered for a Q1 improvement.

**Comment by nonmetalhail** [comment]
Update: This feature was (obviously) never implemented. No ETA on if/when this will be.

**Comment by pratapagiri** [comment]
Need to know when this is planned to be implemented?

**Comment by pratapagiri** [comment]
Is there any workaround to show quality attribute in timeseries chart?

**Comment by nonmetalhail** [comment]
It is not planned for the next quarter. There is no ETA on when it will be.

The only workaround would be listening to tooltipData, associating the data with the quality, and displaying your own tooltip or custom register

**Comment by arongraham-ge** [comment]
Feature not implemented
