### ISSUE TITLE
Property to hide toolbar

### ISSUE THREAD

**Issue by davidsteinberger** [predixdesignsystem/px-vis-timeseries#36]
It be great if we'd have an option like 'hide-toolbar' that allows us to hide the toolbar.
May I send a PR that introduces that boolean option (like hide-register) and uses `_getHideClass()` to hide the toolbar?

**Comment by nonmetalhail** [comment]
I'm pretty sure that is you pass on a blank object into `toolbar-config` that will hide it. @frenchben can you confirm.

Or do you want a hide-toolbar property in addition to this method of hiding?

**Comment by davidsteinberger** [comment]
Thanks for the tip, that's what I'm doing right now. But given that we have _hide-register_, _show-tooltip_, _disable-navigator_ wouldn't it make sense to have an equivalent property for the toolbar too?

**Comment by nonmetalhail** [comment]
Yeah, I agree. We'll look into it.

**Comment by TheWillG** [comment]
Do you mind if I take this one?

**Comment by benoitjchevalier** [comment]
Sure, a `hideToolbar` property would do nicely, you'll have to make sure that all the sizing still works though

**Comment by TheWillG** [comment]
Using a dom-if on the toolbar does throw off the sizing a bit.  Is the drawing wrapper being styled in some way that directly styles the toolbar?
```
<template id="toolbarDomIf" is="dom-if" if="[[!hideToolbar]]">
   <px-vis-toolbar
      id="toolbar"
      current-sub-config='[[toolbarSubConfig]]'
      action-config='{{actionConfig}}'
      within-chart
      chart-margin="[[_internalMargin]]"
      config='{"zoom": true, "pan": true, "tooltip": true}'>
    </px-vis-toolbar>
</template>
```

**Comment by benoitjchevalier** [comment]
the method onIronResize looks at the toolbar size, and a dom if won't remove it from the dom so might need to check the boolean in this function

**Comment by TheWillG** [comment]
Please view my PR for my proposed solution.  The display:none property played nicely and did not interfere with sizing.
