### ISSUE TITLE
Multi-Y: Remove the defaultYaxis when including all series

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-vis-timeseries#43]
**Scenario:**
Testing out multi-Y functionality with 8 Y-axes(4 on each side,right/left) in a chart that has 40 series.
Noticed if you "include-all-series", there is no way to remove the default Yaxis.  The default Y axis seems to take up a spot on the left hand side of the chart causing 5 axis on the left instead of 4.

**Environment:**
Vis1.0.1+TS 1.0.0

**Screenshot:**

![screen shot 2017-03-14 at 6 11 27 pm](https://cloud.githubusercontent.com/assets/10835611/23929224/c1251860-08e1-11e7-8943-58614352f3f6.png)

**Code Snippet:**

          include-all-series
          selection-type= "xy"
          show-tooltip
          tooltip-config='{
              "tooltipStyle": "light"
            }'
          chart-data="[[chartData2]]"
          register-config='{
                "height": 150,
                "type": "vertical"
              }'

          series-config='{
                "firstSerie": {
                  "yAxisUnit": "HOURS",
                  "tickFormat": ".2f",

                  "axis": {
                    "id": "axis1",
                    "number": 5,
                    "side": "right"
                  }
                },
                "secondSerie": {
                  "yAxisUnit": "SECONDS",
                  "tickFormat": ".2f",
                  "x": "Date",
                  "y":"purpleparadestone",
                  "axis": {
                    "id": "axis2",
                    "number": 1,
                    "side": "right"
                  }
                },
                "thirdSerie": {
                  "yAxisUnit": "DAYS",
                  "tickFormat": ".2f",
                  "x": "Date",
                  "y":"yellowparadestone",
                  "axis": {
                    "id": "axis3",
                    "number": 2,
                    "side": "right"
                  }
                },
                "fourthSerie": {
                  "yAxisUnit": "MONTHS",
                  "tickFormat": ".2f",
                  "x": "Date",
                  "y":"redparadestone",
                  "axis": {
                    "id": "axis4",
                    "number": 2,
                    "side": "left"
                  }
                },
                "fifthSerie": {
                  "yAxisUnit": "WEEKS",
                  "tickFormat": ".2f",
                  "x": "Date",
                  "y":"Brownparadestone",
                  "axis": {
                    "id": "axis5",
                    "number": 3,
                    "side": "right"
                  }
                },
                "sixthSerie": {
                  "yAxisUnit": "YEARS",
                  "tickFormat": ".2f",
                  "x": "Date",
                  "y":"Blueparadestone",
                  "axis": {
                    "id": "axis6",
                    "number": 3,
                    "side": "left"
                  }
                },
                "seventhSerie": {
                  "yAxisUnit": "CENTURIES",
                  "tickFormat": ".2f",
                  "x": "Date",
                  "y":"Orangeparadestone",
                  "axis": {
                    "id": "axis7",
                    "number": 4,
                    "side": "right"
                  }
                },
                "eighthSerie": {
                  "yAxisUnit": "MILLISECS",
                  "tickFormat": ".1f",
                  "x": "Date",
                  "y":"Bronzeparadestone",
                  "axis": {
                    "id": "axis8",
                    "number": 4,
                    "side": "left"
                  }
                }
              }'

**Comment by benoitjchevalier** [comment]
That axis on the left looks like the axis for the other 32 series that don't have a config
