### ISSUE TITLE
Chart Navigator Brush Reset Issue When Using Multiple Y-Axes

### ISSUE THREAD

**Issue by kjrdel** [predixdesignsystem/px-vis-timeseries#55]
We are noticing some strange/inconsistent behavior in the px-vis-chart-navigator when using multiple y-axes in the main chart.

When using a single y-axes, we can compress the brush in the chart navigator:

![capture_1](https://user-images.githubusercontent.com/28785823/26939674-0d17f9a2-4c46-11e7-868d-a08034e3fae1.PNG)

And then when the chartData is updated (by adding/removing series), the main plot redraws and the brush in the navigator resets itself to full length:

this.set('chartData', updatedData);
![capture_2](https://user-images.githubusercontent.com/28785823/26939826-9466e3f0-4c46-11e7-8231-8f709e30ba74.PNG)

However, when using multiple y-axes with the same data, we can compress the brush:

![capture_3](https://user-images.githubusercontent.com/28785823/26939947-f071bb16-4c46-11e7-823c-476bd928321a.PNG)

And then when the chartData is updated, the main plot redraws properly, but the brush in the navigator _does not_ reset itself to full length:

this.set('chartData', updatedData);
![capture_4](https://user-images.githubusercontent.com/28785823/26940045-3f5f72e0-4c47-11e7-8509-38eaf6cb58b3.PNG)

The same behavior occurs when switching between a single y-axis and multiple y-axes (with the same data) by updating the axes in the seriesConfig:

this.set('seriesConfig', updatedConfig);

Is this expected behavior?  It seems inconsistent.

**Comment by benoitjchevalier** [comment]
Hello,

I've been having a look at it this morning but can't seem to be able to reproduce on the latest (this can be seen [here](https://www.predix-ui.com/px-vis-demos/px-vis-demos/dynamic_add.html) by using the `toolbar to modify series` option).

Are you still seeing this issue?

**Comment by kjrdel** [comment]
No longer seeing the navigator issue with latest version 2 (v 2.1.3).  However, there are some JavaScript errors when toggling between single/multiple axes:

![capture](https://user-images.githubusercontent.com/28785823/29229887-94a7e39c-7eae-11e7-8301-f479ba3c2456.PNG)

Have not been able to test with version 3 yet as some of the new redesign themes are not compatible with our app.

**Comment by nonmetalhail** [comment]
We would need more information to diagnose this but at this point we probably won't fix given the release is v3. If you give me info we can check v3 for this issue

**Comment by kjrdel** [comment]
I am seeing this when refreshing the chart canvas and navigator after toggling the seriesConfig between multiple and a single y-axis.  For example, plot two separate series using two different y-axes:

`this.set('chartData', data)`
`this.set('seriesConfig', {series1: {name: "series1", ...}, series2: {name: "series2", axis: {id: "axis2", side: "right", number: 2}, ...}}`

Where "series1" uses the default axis.  Now, plot the same values within the same chart instance using a single y-axis:

`this.set('seriesConfig', {series1: {name: "series1", ...}, series2: {name: "series2", ...}}`

and allow the chart canvas and navigator to redraw.  Error shows up during the redraw process.  Oddly, I do not see it when going from one y-axis to multiple, just multiple to single.

Does this help?

**Comment by arongraham-ge** [comment]
closing as original issue resolved
