### ISSUE TITLE
The theme color for the tooltip text is not applied for the date nor the value

### ISSUE THREAD

**Issue by stephanepilla** [predixdesignsystem/px-vis-timeseries#63]
The tooltip text color is not consistent : 
the series name seems ok but the date and the value are always black.
The theme color doesn't seem to be applied for the date and the value.

This is especially visible with Predix dark theme. 

Px-Vis version : 3.1.17
Px-Vis-Timeseries version : 3.0.4

![capture d ecran 2017-09-06 a 13 45 18](https://user-images.githubusercontent.com/17046306/30110457-6e5b3016-930a-11e7-8101-f218331d6cfa.png)

**Comment by benoitjchevalier** [comment]
Hello,

if you are manually setting your theme you should be able to configure those through --px-tooltip-light-text-color.

If you are using the px dark theme then you will have to change the px-vis-tooltip `style`  property to 'light'. This is a consequence of how the vis tooltip has been built in the past, although it should probably now be changed to be style purely through theming

**Comment by randyaskin** [comment]
@benoitjchevalier the `tooltipStyle` property for light/dark was removed in v1 during the refresh, it is purely handled with CSS vars now

**Comment by benoitjchevalier** [comment]
Although true for the px-tooltip itself the vis tooltip still uses it to style the internal register within the tooltip. I just tried setting it to 'dark' in the dark theme and that made the date and value white

**Comment by stephanepilla** [comment]
It seems that the `--px-tooltip-light-text-color` css variable is used in any case : I'm able to change the tooltip text color of a particular chart of my UI (by overriding this css variable) regardless of the light or dark theme I import in my UI.

However, the px-theme / px-dark-theme sass components are now using another variable name : `--px-tooltip-text-color`.

So it seems to be a css variable name mismatch between px-vis-tooltip and px-theme.
Could you update px-vis-tooltip to use the actual latest tooltip theme variables?

**Comment by benoitjchevalier** [comment]
Switching `tooltipStyle`(in tooltip-config) will change what css var is used. So right now if you switch `tooltipStyle` to 'dark' then it should use --px-tooltip-text-color instead of --px-tooltip-light-text-color. This is not done automatically when switching theme but has to be done manually. The vis tooltip automatically fallback on black/white if those css vars are not defined.

It kind of sucks so we need to look at how we're going to change that in the future :)

**Comment by stephanepilla** [comment]
Yes, it would be good to rely only on the theme and not on the tooltipstyle anymore.

Ok thanks for those explainations.

**Comment by arongraham-ge** [comment]
closing as setting variables is a valid workaround while we look at updating the theme function
