### ISSUE TITLE
MultiY: Event Marker icons should be clipped so they don't go past the Y axes.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-vis-timeseries#69]
When you pan around in a multiY TS chart that has event marker icons,  the event markers' icons can be panned all the way out of the chart past the axes.  Should they be clipped at the axis?
 Screenshot below.

### Environment:
TS: 3.2.5
Vis: 4.4.6

Browser: Chrome

### Screenshot:

![screen shot 2017-11-14 at 12 01 02 pm](https://user-images.githubusercontent.com/10835611/32802595-5ec5693a-c935-11e7-8a7a-cfe6e2642700.png)

**Comment by nonmetalhail** [comment]
Fired in v4
