### ISSUE TITLE
Seeing multiple series after zoom in on x-axis.

### ISSUE THREAD

**Issue by krathslag** [predixdesignsystem/px-vis-timeseries#74]
When a user zooms in on the x-axis multiple times on a single series, after a certain point the chart displays multiple series. The number of series displayed increases with each subsequent zoom-in.

I'm seeing this behavior in Google Chrome (64.0.3282.186), Windows 10.  I'm seeing it in our application and on the Predix px-vis-timeseries demo page. (see screenshots below.)

![image](https://user-images.githubusercontent.com/21205173/37609801-10415aaa-2b6c-11e8-818e-e04ca09cdee5.png)
![image](https://user-images.githubusercontent.com/21205173/37609816-161e23e0-2b6c-11e8-8656-c8a87cfa3a62.png)
![image](https://user-images.githubusercontent.com/21205173/37609824-1c8503ca-2b6c-11e8-83ad-cab2a64d85e8.png)
![image](https://user-images.githubusercontent.com/21205173/37609832-23d3c1de-2b6c-11e8-99f5-59649bdc64e6.png)

**Comment by benoitjchevalier** [comment]
Thanks for reporting this issue, we released a new version of the vis framework with a fix for it: `4.7.9`
