### ISSUE TITLE
Display Data Quality in the px-vis-timeseries Chart

### ISSUE THREAD

**Issue by pratapagiri** [predixdesignsystem/px-vis-timeseries#75]
This is an enhancement request.

We have timeseries data with "Data Quality" attribute, as defined in the 
[https://docs.predix.io/en-US/content/service/data_management/time_series/using-the-time-series-service](https://docs.predix.io/en-US/content/service/data_management/time_series/using-the-time-series-service)

The "Data Quaity" attribute will contain values 0,1,2,3

In the px-vis-timeseries chart, we would like to display the "Data Quality" attribute value in the tooltip (or) in the Register config.

**Comment by nonmetalhail** [comment]
Already open #16. Closing this one
