### ISSUE TITLE
No usage or example of 'labelRotation' property for axisConfig seems to be available

### ISSUE THREAD

**Issue by Sd100** [predixdesignsystem/px-vis-timeseries#76]
Found out how to set xAxisConfig properties for **px-vis-timeseries** chart through API and developer community network. 
There is no documentation or example of how to set '**labelRotation**' for xAxisConfig in the above mentioned component

Tried : myChart.set('xAxisConfig',{labelRotation: 45});
where, myChart is px-vis-timeseries chart. 
Correct me if i am missing something. 
P.S.: Many such properties which d3 provides support for, but do not seem to be exposed in 'px-vis-timeseries' API or are not documented.

**Comment by benoitjchevalier** [comment]
Hello,

you might want to read this guide on how to configure charts: https://www.predix-ui.com/#/develop/vis/configure-charts . In particular it touches on how to configure sub components for the chart, in your case axis.

You can then look at the axis API and see all the configuration options: https://www.predix-ui.com/#/elements/vis/px-vis-framework/px-vis-axis

In this specific case I looked at the code and found a bug where `labelRotation` wouldn't be applied when `labelPosition` is "center", which is the default. So you were doing the right thing but found a bug

**Comment by Sd100** [comment]
Hello,
Thank you for pointing out the solution. I did go through axis API; but the default value of 'labelPosition' is 'after' in my chart. Still the 'labelRotation' property is not being set through xAxisConfig. Also, the 'labelPosition' is not being modified to other possible value like 'before' and 'center'.  Currently the xAxisType is 'ordinal' in this case. Can somebody give insight on this problem? Maybe some other property is also required.

**Comment by nonmetalhail** [comment]
Can't have ordinal xAxisType  on this chart. Use XY instead
