### ISSUE TITLE
textAnchor not being set from xAxisConfig for px-vis-timeseries leading to overlap of labels onto axis

### ISSUE THREAD

**Issue by Sd100** [predixdesignsystem/px-vis-timeseries#77]
Hi,
After setting **labelPosition** as '**before**' and labelRotation at -65 degrees via xAxisConfig, i get the result on x-axis as shown in below image:
![image](https://user-images.githubusercontent.com/37838320/38022489-4c4831bc-329d-11e8-8e64-212aade990b1.png)

But, how do i set **textAnchor** as 'end' using xAxisConfig and increase the distance between the labels and the axis for cleaner view of axis-labels( not the way they are overlapping on the axis right now in the image). Is this because of the particular labelPosition value i am using as mentioned above?
I tried:
xAxisConfig:{
"text-anchor":"end"
}

**Comment by Sd100** [comment]
Can somebody help out with the problem mentioned above?.. 
I am looking forward to know how to solve overlap problem. Let me know if i am missing some property from the API docs.

**Comment by nonmetalhail** [comment]
There is no textAnchor property. See:
https://www.predix-ui.com/#/elements/vis/px-vis-framework/px-vis-axis

**Comment by Sd100** [comment]
Hello,
Thank you for pointing out; but is there a way to solve the labels of points on axis and axis itself are overlapping as shown in the above image. is there a property to make the labels look as they are shown in image but more legible & not overlap on the axis ?
Currently, properties i had set which resulted in the above output(shown in image uploaded) are:
labelPosition:"before" and labelRotation:-65 (degrees) in xAxisConfig.
Am i missing some property to avoid the overlap shown in the image? Please let me know what can be done.
