### ISSUE TITLE
Same values repeating on y axis when ticks format is set to 'd' and chart-extents 'dynamic'

### ISSUE THREAD

**Issue by ArjunAce** [predixdesignsystem/px-vis-timeseries#78]
When tickFormat of y-axis-config is set to "d", same values are repeating multiple times on the y axis.
Expected behavior:
with chart-extents='{"x":["dynamic","dynamic"],"y":[0,**_8_**]}'
![defect2](https://user-images.githubusercontent.com/29628660/38027182-81175f12-32ac-11e8-8435-1ed5c0d993ce.png)

Actual behavior:
with chart-extents='{"x":["dynamic","dynamic"],"y":[0,**_"dynamic"_**]}'
![defect1](https://user-images.githubusercontent.com/29628660/38027179-7f3cc696-32ac-11e8-8e0d-0aa9771934e4.png)

I understand the actual behavior that is being exhibited due to the **chart-extents.y** set to "**dynamic**" and **tickFormat** of **y-axis-config** set to "**d**", but I expect it to accordingly avoid repeating values and dynamically set a higher value to **chart-extent.y**

PS: I want the tickFormat in y-axis-config to be "d" so as to only have whole numbers on the y axis.
Environment:
component version number: 3.4.4
Browser: Google Chrome v65.0.3325.181 (Official Build) (32-bit)
OS: Windows 10 64-bit

**Comment by benoitjchevalier** [comment]
the tickformat only impacts the formating of the ticks, not their number/values. d3 picks appropriate values for the ticks, but if your range is small and you only want integers you're going to run into this issue. You could manually calculate the values of your ticks to work around it (in this case setting them to 1, 2 and 3 for example).

The dynamic chart extents is calculated from the data, if you want it to be higher than your max values then you'll have to do the calculation on your side

**Comment by ArjunAce** [comment]
Alright. Thanks!
