### ISSUE TITLE
Horizontal scroll on register

### ISSUE THREAD

**Issue by shrau94** [predixdesignsystem/px-vis-timeseries#79]
Hi,

Came across the following scenario:

## Expected behavior and actual behavior:
Actual behavior: horizontal scroll is visible.

## Steps to reproduce the problem:
give a seriesConfig and charData in such a way that there are 8 legends with big names.

## Environment 
component: 3.4.3

## Screenshots:
![image](https://user-images.githubusercontent.com/10210384/38417702-faf90202-39b6-11e8-8135-d966a2294589.png)

## Code examples help us better understand the issue:
registerConfig is:
`"register-config":{
      "type":"horizontal",
      "preventMinSize":true,
       "truncationLength": -1
}`
seriesConfig is:
`"series-config":{"y0":{"name":"MOTOR-CURRENT","x":"timeStamp","y":"y0","yAxisUnit":"Amp","axis":{"id":"axis1","side":"left","number":"1"}},"y1":{"name":"PUMP-INTAKE-TEMP","x":"timeStamp","y":"y1","yAxisUnit":"Cel","axis":{"id":"axis2","side":"right","number":"1"}},"y2":{"name":"PUMP-INTAKE-PRESSURE","x":"timeStamp","y":"y2","yAxisUnit":"N","axis":{"id":"axis3","side":"left","number":"2"}},"y3":{"name":"PUMP-DISCHARGE-PRESSURE","x":"timeStamp","y":"y3","yAxisUnit":"N","axis":{"id":"axis3","side":"left","number":"2"}},"y4":{"name":"PUMP-DISCHARGE-PRESSURE","x":"timeStamp","y":"y4","yAxisUnit":"N","axis":{"id":"axis3","side":"left","number":"2"}},"y5":{"name":"OPERATING-FREQUENCY","x":"timeStamp","y":"y5","yAxisUnit":"Hz","axis":{"id":"axis4","side":"left","number":"3"}},"y6":{"name":"TOTAL-LIQUID-FLOWRATE","x":"timeStamp","y":"y6","yAxisUnit":"rpm","axis":{"id":"axis5","side":"right","number":"2"}}}`

Is there a way such that when there is no sufficient width then the legends that do not fit comes on the next line? And at the same time the full name of the legends are visible.

**Comment by nonmetalhail** [comment]
That is expected behavior
