### ISSUE TITLE
for px-vis-timeseries overlap of labels onto axis- how to avoid overlapping

### ISSUE THREAD

**Issue by Sd100** [predixdesignsystem/px-vis-timeseries#80]
Hi,
![image](https://user-images.githubusercontent.com/37838320/38488598-9a1166ee-3c01-11e8-9552-8360544af370.png)

Is there a way to solve the labels of points on axis and axis itself are overlapping as shown in the above image. is there a property to make the labels look as they are shown in image but more legible & not overlap on the axis ?

Currently, properties i had set which resulted in the above output(shown in image uploaded) are:
**labelPosition:"before"** and **labelRotation:-65** (degrees) in xAxisConfig.

Am i missing some property to avoid the overlap shown in the image? Please let me know what can be done.

I had logged an issue linked at :
https://github.com/predixdesignsystem/px-vis-timeseries/issues/77
But couldn't find a way to reopen the closed issue; so logging again since i am still kid of stuck in the above mentioned problem.

**Comment by benoitjchevalier** [comment]
You can try offsetting them more by using `labeltranslation`. Consider also formatting your tick values differently so that they're smaller (not sure what is happening here but your values look odd on the X axis for a timeseries)

**Comment by Sd100** [comment]
Hi,
Actually the values shown in the above image are just dummy values. So the overlapping problem of axis labels on the x-axis got resolved by property 'labelTranslation'. Thank you for the suggestion. 

I just had 2 more queries:

- If we try xAxisType as ordinal on prx-vis-timeseries chart and plot the chartData, following result is seen:

**Comment by nonmetalhail** [comment]
Answered in the other issues you opened
