### ISSUE TITLE
Axis title overlaps the slanted axis labels in px-vis-timeseries

### ISSUE THREAD

**Issue by Sd100** [predixdesignsystem/px-vis-timeseries#81]
Hi,
The region encircled in the figure depicts my issue with px-vis-timeseries chart.
How to bring the axis title lower in such a way that it is responsive. My chart's height is fixed  and width is not fixed. 
![sampleimg](https://user-images.githubusercontent.com/37838320/38673572-57a578f2-3e6f-11e8-942a-d4e7f3baeb61.PNG)

**Tried using titleLocation  property as follows in xAxisconfig of px-vis-timeseries chart:**
"titleLocation":{
"x": 400,
"y": 240,
"r": 0,
"anchor": "middle"
}
But here i do not want to fix value of x, and the axisconfig does not seem to read value of anchor property even if i set it to other options such as "end". Also, tried giving only "y" and "anchor" property in **titleLocation** but an error is shown in console since "x" is not defined.
can somebody help me figure out is this solvable - I need the title of the axis lowered so that it does not overlap with the titled axis labels as shown in figure, with obeying responsiveness with-wise??

I tried all solutions of API. Still feel free to suggest some solution or workaround for this.

**Comment by nonmetalhail** [comment]
There is no automatic way. You must set it using titleLocation as you are doing

**Comment by Sd100** [comment]
Ok, thanks for confirming.
