### ISSUE TITLE
Divide all values on y-axis always by 1000 to get in 'k' form

### ISSUE THREAD

**Issue by Sd100** [predixdesignsystem/px-vis-timeseries#83]
Hi,
1)When the values of points on y-axis are in the order of 10^3, how to make the data divide by 3 if we know data on that axis is going to be of that order always and we want to see in form of divided by 1000; eg: 25000 as 25k, 13500 as 13.5k, and so on.
![image](https://user-images.githubusercontent.com/37838320/39421272-ef2f6196-4c85-11e8-95bc-9892b67e6031.png)

2) Also, if the data value plotted on y-axis is too long, the space alloted for y-axis does not increase after a certain limit making it look messy the way shown in above snapshot. The snapshot is taken by modifying dummy data on px-vis-timeseries demo page.

**Comment by benoitjchevalier** [comment]
1) please read this guide: https://www.predix-ui.com/#/develop/vis/configure-axis on how to configure the format of those values
2) please increase the left margin appropriately (the chart won't automatically adjust the margin)

**Comment by Sd100** [comment]
Thank you so much, it did help.
