### ISSUE TITLE
Overlapping Canvas

### ISSUE THREAD

**Issue by dlernz** [predixdesignsystem/px-vis-timeseries#84]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
Expected: See tooltip when over over marker
Actual: Tooltip does not show after hover over

Highlighter canvas on top of marker canvas. Mouse events for markers are not being recognized. Spoke with Benoit Chevalier about issue. 
## Steps to reproduce the problem:
1. Navigate to https://www.predix-ui.com/px-vis-demos/px-vis-demos/dynamic_add.html
2. Generate data
3. Select 'Add Crosshair Data', 'Show Tooltip', 'Add Some Markers', and 'Render to Canvas'
4. Create chart
5. Hover over marker on generated chart (tooltip does not show) 
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
1. px-vis: 4.7.11
2. px-vis-timeseries: 3.4.1
3. Chrome: 66.0.3359.139
## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by nonmetalhail** [comment]
This works in latest version of vis and timeseries

**Comment by benoitjchevalier** [comment]
Last I tried it didn't. Need to have crosshair + markers enabled on dynamic generator

**Comment by nonmetalhail** [comment]
fixed in v5.0.4 of vis
