### ISSUE TITLE
Scaling on y-axis seems unpredictable and shows repetitive values

### ISSUE THREAD

**Issue by Sd100** [predixdesignsystem/px-vis-timeseries#85]
Hi,
Please find images attached for the behavior of px-vis-timeseries seen when value on that are as given:
1) [stb/d] - shows 880 at all tick points on y-axis and tickFormat is .2s:
![screenshot2](https://user-images.githubusercontent.com/37838320/40218856-a8c99154-5a90-11e8-840f-ee5155048443.png)

2) [stb/d] - value of ticks when value ingested is 40.1 and tickFormat is .2s:
![screenshot1](https://user-images.githubusercontent.com/37838320/40218898-d167ae7a-5a90-11e8-9afa-afc734daaf9c.png)

Here, i do want to keep format .2s, since values might go in 10^3 scale in some cases. How do i endure values do not repeat on same axis or is this the expected behavior of px-vis-timeseries?

**Comment by arongraham-ge** [comment]
@Sd100 can you supply us with the dataset you used to create the charts so we can use it to validate the issue and test possible fixes.
