### ISSUE TITLE
A tooltip icon is shown even when the event data is empty.

### ISSUE THREAD

**Issue by kishan2695** [predixdesignsystem/px-vis-timeseries#86]
**Issue**: 
The event tool tip icon is shown even when an empty array is passed to the event data property of the px-vis-timeseries component. 

**How to reproduce**: 
1. Go to the https://www.predix-ui.com/#/elements/vis/px-vis-timeseries
2. Replace the existing data by [{ }].
3. A tool tip icon appears at the top left corner of the chart.
4. This icon stays until a non-empty array is passed to the event data property.

**Expected behaviour**: 
When the event data object is empty ,no tool tip icon should appear on the chart.

Relevant screenshots have been attached which show the different values being passed to the event data property  and how the tool-tip icon appears on the left top corner.

First screenshot: No value passed
Second screenshot: Empty Array Passed
Third Screenshot: Unwanted tool tip icon

<img width="471" alt="1" src="https://user-images.githubusercontent.com/19781988/40778617-684ebe10-64ef-11e8-96d1-791fd1eaaf0a.PNG">
<img width="496" alt="3" src="https://user-images.githubusercontent.com/19781988/40778623-6d89eb48-64ef-11e8-9746-7b579c2613e1.PNG">
<img width="566" alt="2" src="https://user-images.githubusercontent.com/19781988/40778629-73a660ba-64ef-11e8-8b87-7640a455d0ef.PNG">

**Comment by bentwonk** [comment]
Hi Kishan, there have been a number of updates to the PX libraries recently, and I can no longer repeat this issue.
Could you please confirm it is fixed, or provide more details on how to repeat.

<img width="918" alt="screen shot 2019-01-08 at 9 28 31 pm" src="https://user-images.githubusercontent.com/1641837/50859980-ac628e00-138c-11e9-90b8-8b1684ea9f13.png">
