### ISSUE TITLE
Zooming in and out use different scales

### ISSUE THREAD

**Issue by shalarim** [predixdesignsystem/px-vis-timeseries#91]
If I click the zoom + button to zoom in and then click the zoom - button I do not return to the original view.

Zooming in appears to be 50% (split evenly around centre point) 
Zooming out also seems to be 50% but as it has a smaller initial scale this does not return it to the original position.

Example:
Scale 0-10 (range 10)
Zoom In --> 2.5 - 7.5 (range 5)  Increment = Range / 2 = 5 Split evenly from start and end = 2.5 each end
Zoom Out --> 1.25 - 8.75 ( range 7.5)  Increment = Range / 2 = 2.5 Split evenly from start and end = 1.25 each end

**Comment by benoitjchevalier** [comment]
FYI you can work around it by setting your own values on the chart: `zoomInPercentage` and `zoomOutPercentage` (as you stated they both default to 0.5)

**Comment by shalarim** [comment]
Ahhh, didn't see those. Thank you

**Comment by shalarim** [comment]
I adjusted my local settings to 0.5 in and 1 out.  This equates to halving when zooming in and doubling when zooming out. I would personally recommend changing the defaults to this, But feel free to close issue.
